name: 'Apt-Cache-Action'
description: Cache Apt Packages
author: Eeems
branding:
  icon: archive
  color: orange
inputs:
  packages:
    description: List of packages to install and cache
    required: true
  path:
    description: Location to cache deb files
    required: false
    default: .aptcache
runs:
  using: composite
  steps:
    - name: Setup Apt for caching
      shell: bash
      run: |
        sudo apt-get update -yq
        aptHash(){ echo "$1-$(apt-cache policy "$1" | grep -oP '(?<=Candidate:\s)(.+)')"; }
        export -f aptHash
        hash=$(echo "${{ inputs.packages }}" | xargs -rI {} bash -c 'aptHash {}' | tr '\n' '-')
        echo "packagesHash=${hash%-}" >> $GITHUB_ENV
    - name: Cache deb files
      uses: actions/cache@v4
      with:
        path: ${{ inputs.path }}
        key: apt-cache-${{ env.packagesHash }}
        restore-keys: |
          apt-cache-
    - name: Restore deb files from cache
      shell: bash
      run: |
        sudo apt-get clean -yq
        if compgen -G "${{ inputs.path }}/*.deb" > /dev/null; then
          sudo cp -l ${{ inputs.path }}/*.deb /var/cache/apt/archives
        fi
        sudo apt-get install -yq ${{ inputs.packages }}
        mkdir -p ${{ inputs.path }}
        sudo cp -l /var/cache/apt/archives/*.deb ${{ inputs.path }}
